### ISSUE TITLE
Include Google fonts as static files

### ISSUE THREAD

**Issue by icidasset** [fission-codes/landing-page#17]
Because, IPFS.

(FYI, Google fonts are cached automatically through the service worker)

**Comment by bmann** [comment]
I'm going to leave this here, because I think we have a related discussion happening elsewhere. @walkah @icidasset can you link to it? Discussion in fission-kit?

**Comment by icidasset** [comment]
> I'm going to leave this here, because I think we have a related discussion happening elsewhere. @walkah @icidasset can you link to it? Discussion in fission-kit?

I don't think we have an issue for this anywhere. That said, we do have the fonts as static files in the fission kit, and there's an easy copy-font-files command (see kit readme). Using that here now.
