### ISSUE TITLE
Linked invisible column

### ISSUE THREAD

**Issue by expede** [fission-codes/landing-page#80]
Across desktop browsers (FF, Chrome, Safari), there's invisible columns that are clickable. The one pictured below goes to `blog.fission.codes`, and there's another that opens the swag store in a new tab.

<img width="307" alt="Screenshot 2023-01-04 at 12 29 01" src="https://user-images.githubusercontent.com/1052016/210644305-369e6a83-f695-408a-84e3-313914d7ba4c.png">

It seems to run from roughly the hero image to the bottom of the page on the left side.

**Comment by avivash** [comment]
Thanks for logging this @expede. I'm not sure if I reproduced the exact issue you were describing, but I think I may have just deployed a fix for it if you'd like to test it again. thanks!

**Comment by expede** [comment]
@avivash seems better now — thanks for the quick fix!!
