### ISSUE TITLE
Move to node16 as a runner for actions

### ISSUE THREAD

**Issue by bmann** [fission-codes/landing-page#91]
> The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by walkah** [comment]
Done: https://github.com/fission-codes/publish-action/blob/v1/action.yml#L35
