### ISSUE TITLE
Get audio file link from page attributes

### ISSUE THREAD

**Issue by bmann** [fission-codes/landing-page#93]
I heavily commented the podcast feed file -> https://github.com/fission-codes/landing-page/blob/master/src/podcast.njk

The one thing that is funky right now, is that you have to get the link to the audio file by manually placing it in the Facebook description of the Ghost post.

Instead, it should be something like -- when audio file is downloaded, add it's name as metadata to the page. So this line for enclosure:

https://github.com/fission-codes/landing-page/blob/b01b73fa9ceb050fc4e6afbbc82232b4c60ecc2b/src/podcast.njk#L45C22-L45C22

Should instead be `{{ podcast.enclosure }}` where it's simply the file name -- and we can manually prepend `fission.codes/relativeAudioFile/` to it.

**Comment by avivash** [comment]
Done as part of https://github.com/fission-codes/landing-page/commit/a974718b5401214f9fbd57dac165e2595b76553b.

I'm just getting the fileName directly from the audio file, but can pull it from a ghost field instead if we want.

Podcast image is being resized and saved locally now too 👍🏼

**Comment by bmann** [comment]
Sweet. Thanks @avivash.
