### ISSUE TITLE
Ghost Pages are stripping Headers

### ISSUE THREAD

**Issue by heybeckyv** [fission-codes/landing-page#97]
Leaf pages created in Ghost are not displaying the header image/banner. For example, [Devconnect Istanbul](https://fission.codes/devconnect-istanbul/) shows a -- line at the top and no header.

**Comment by avivash** [comment]
@heybeckyv this is done now 👍🏼 

<img width="1052" alt="image" src="https://github.com/fission-codes/landing-page/assets/1179291/a5366ee3-cc30-4a40-b9bb-0d360f334ae4">

**Comment by heybeckyv** [comment]
Hi @avivash! Is there a way to remove the -- under the banner and above the title? It will be the same on the fission.codes/events page.

**Comment by avivash** [comment]
@heybeckyv yep, done!

**Comment by avivash** [comment]
@heybeckyv I'm going to close this now, but feel free to re-open a new issue if other things pop up :)
